# Generated by Django 3.1.5 on 2021-02-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sold_by'),
        ('orders', '0002_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='soldproducts', to='products.product')),
            ],
        ),
    ]
