# Generated by Django 3.1.5 on 2021-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_soldorderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldorderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
