# Generated by Django 3.1.5 on 2021-02-02 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_soldorderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldorderitems',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
