# Generated by Django 3.1.5 on 2021-02-10 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
        ('orders', '0005_soldorderitems_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldorderitems',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soldorderitems',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='soldorderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldproducts', to='products.product'),
        ),
    ]
