# Generated by Django 3.1.5 on 2021-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210218_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldorderitems',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='soldorderitems',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='soldorderitems',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
