# Generated by Django 3.1.5 on 2021-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210218_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldorderitems',
            name='sold_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
