# Generated by Django 3.1.5 on 2021-02-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_timestamp'),
        ('orders', '0010_auto_20210219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldorderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldproducts', to='products.product'),
        ),
    ]
