# Generated by Django 3.1.5 on 2021-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210219_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldorderitems',
            name='item',
            field=models.CharField(max_length=255),
        ),
    ]
